# Generated by Django 5.0.2 on 2024-02-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pro_image",
            field=models.FileField(null=True, upload_to="products"),
        ),
    ]
