# Generated by Django 5.0.2 on 2024-03-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_product_pro_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_user", models.CharField(default=None, max_length=250)),
                ("cart_name", models.CharField(max_length=250)),
                ("cart_price", models.CharField(max_length=250)),
                ("cart_image", models.FileField(null=True, upload_to="")),
                ("cart_qty", models.IntegerField()),
                ("cart_amount", models.FloatField()),
            ],
        ),
    ]
