# Generated by Django 5.0.2 on 2024-03-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_price",
            field=models.FloatField(max_length=250),
        ),
    ]
