# Generated by Django 5.0.2 on 2024-03-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_alter_cart_cart_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ord_user", models.CharField(default=None, max_length=250)),
                ("ord_name", models.CharField(max_length=250)),
                ("ord_price", models.FloatField(max_length=250)),
                ("ord_image", models.FileField(null=True, upload_to="")),
                ("ord_qty", models.IntegerField()),
                ("ord_amount", models.FloatField()),
                ("ord_type", models.CharField(max_length=10)),
                ("ord_status", models.IntegerField()),
            ],
        ),
    ]
