# Generated by Django 5.0.2 on 2024-03-07 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_order_ord_address_alter_order_ord_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="ord_type",
            new_name="ord_dlvtype",
        ),
    ]
