# Generated by Django 5.0.2 on 2024-03-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_rename_ord_type_order_ord_dlvtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ord_status",
            field=models.IntegerField(null=True),
        ),
    ]
