# Generated by Django 5.0.2 on 2024-03-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_alter_order_ord_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="cart_proid",
            field=models.IntegerField(null=True),
        ),
    ]
